### ISSUE TITLE
Error after plugin install (and PhpStorm restart)

### ISSUE THREAD

**Issue by jubianchi** [phpmetrics/PhpMetrics-jetbrains#1]
Here are the error messages:

```
15:01:01 PluginException: cannot create class "hal.phpmetrics.idea.RunPhpMetricsAction" [Plugin: com.hal.phpmetrics.id]
15:01:03 Throwable: Null child action in group  () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=hal.phpmetrics.idea.run.id
15:01:19 Throwable: Null child action in group  () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=hal.phpmetrics.idea.run.id
```

About PhpStorm:

```
PS-138.567
JRE: 1.6.0_65
JVM Java HotSpot 64bit By Apple
```

Ok, I'm using an EAP :/

**Comment by misakuo** [comment]
hi, so sorry to commit comment here. I'm developing a plugin in IDEA but occur the same bug `Null child action in group Main Toolbar () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=Moxun.generator` in plugin.xml, I registerd plugin to group `MainToolBar`, it work fine but crashed in some IDE. my develop env is osx EI Captain & JDK1.8 & IDEA 14, and compile it with Java language 6
