### ISSUE TITLE
Where is "Analyze" menu in PHPStorm?

### ISSUE THREAD

**Issue by Slach** [phpmetrics/PhpMetrics-jetbrains#3]
```
A new action "Run PhpMetrics on the selected folder" is available in the "Analyze" menu.
```

Where is "Analyze" menu in PHPStorm?
Maybe need screenshot for clean understanding?

**Comment by JavierCane** [comment]
You can also go to the Keymap preferences and assign a shortcut (for instance: `Cmd+Ctrl+M`)

**Comment by AndrianD** [comment]
Under mac it has changed a little: `Code > Run PhpMetrics on selected folder`
